# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 

    runs-on: self-hosted #runs on my self hosted vm runner
    strategy:
      matrix:
        java: [ '17' ] #add more java versions later

    steps:
      - uses: actions/checkout@v3 #pull my forked repo into runner
      - name: Set up JDK ${{matrix.java}} #
        uses: actions/setup-java@v4 #setup
        with:
          java-version: ${{matrix.java}} #install java version in matrix
          distribution: 'adopt' #package and distribute jdk; adopt one of many companies that package jdk
          #cache: maven #remember what we downloaded last time so dont redo. Maven downloads .jar files every time it builds
      - name: Build with Maven Wrapper
        run: ./mvnw -B package #download and run a specific pinned version of maven in the repo
      - name: Upload build artifact
        uses: actions/upload-artifact@v4 #uploud output of maven build(the artifact)
        with:
          name: spring-petclinic-jar
          path: target/*.jar
#.jar file is a file with all the pieces your app needs to run
  upload:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-petclinic-jar
      - name: Upload to Nexus
        env: 
          NEXUS_USER: ${{ secrets.NEXUS_USERNAME }} #could just add this normally
          NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          curl -v -u NEXUS_USER:NEXUS_PASS \
            --upload-file *.jar \
            http://http://172.16.58.135:8081/repository/maven-releases/spring-petclinic/${{ github.run_number }}/spring-petclinic-${{ github.run_number }}.jar






    
